version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: khaos
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
  redis:
    image: redis:alpine
  worker:
    build: .
    command: ["python", "app/worker.py"]
    depends_on:
      - redis
      - db
    env_file: .env
    volumes:
      - .:/app
volumes:
  pgdata:
